name: Build code base
Description: Workflow action to build the code base

inputs:
  only-affected:
    default: false

runs:
  using: composite
  steps:

    - name: Build project [all]
      if: ${{ inputs.only-affected == 'false' }}
      shell: bash
      run: pnpm build

    - name: Build project [affected]
      if: ${{ inputs.only-affected == 'true' }}
      shell: bash
      run: pnpm --filter "...[origin/main]" build 