/**
 * @fileoverview Sample employee data for the AG Grid demo.
 *
 * In a real application this would come from an API via a React Query hook
 * or a route `clientLoader`. Kept as a static fixture here so the demo
 * works without a backend.
 */

import type { Employee } from './types';

/** Sample employee records used to populate the AG Grid demo. */
export const EMPLOYEES: readonly Employee[] = [
  {
    id: 1,
    name: 'John Doe',
    department: 'Engineering',
    salary: 75_000,
    startDate: '2022-01-15',
    active: true,
  },
  {
    id: 2,
    name: 'Jane Smith',
    department: 'Design',
    salary: 68_000,
    startDate: '2021-08-22',
    active: true,
  },
  {
    id: 3,
    name: 'Bob Johnson',
    department: 'Product',
    salary: 82_000,
    startDate: '2020-03-10',
    active: false,
  },
  {
    id: 4,
    name: 'Alice Brown',
    department: 'Engineering',
    salary: 78_000,
    startDate: '2023-02-10',
    active: true,
  },
  {
    id: 5,
    name: 'Tom Wilson',
    department: 'Marketing',
    salary: 65_000,
    startDate: '2022-11-05',
    active: true,
  },
  {
    id: 6,
    name: 'Emma Davis',
    department: 'Design',
    salary: 72_000,
    startDate: '2021-04-18',
    active: true,
  },
  {
    id: 7,
    name: 'Michael Lee',
    department: 'Product',
    salary: 85_000,
    startDate: '2019-09-30',
    active: false,
  },
  {
    id: 8,
    name: 'Sarah Taylor',
    department: 'Engineering',
    salary: 80_000,
    startDate: '2023-06-12',
    active: true,
  },
  {
    id: 9,
    name: 'David Clark',
    department: 'Sales',
    salary: 70_000,
    startDate: '2022-07-25',
    active: true,
  },
  {
    id: 10,
    name: 'Laura Martinez',
    department: 'Design',
    salary: 69_000,
    startDate: '2020-12-01',
    active: false,
  },
  {
    id: 11,
    name: 'James White',
    department: 'Engineering',
    salary: 90_000,
    startDate: '2021-03-15',
    active: true,
  },
  {
    id: 12,
    name: 'Emily Harris',
    department: 'Marketing',
    salary: 67_000,
    startDate: '2023-01-20',
    active: true,
  },
  {
    id: 13,
    name: 'Chris Evans',
    department: 'Product',
    salary: 83_000,
    startDate: '2020-05-08',
    active: true,
  },
  {
    id: 14,
    name: 'Olivia King',
    department: 'Sales',
    salary: 71_000,
    startDate: '2022-09-14',
    active: true,
  },
  {
    id: 15,
    name: 'Daniel Moore',
    department: 'Engineering',
    salary: 87_000,
    startDate: '2019-11-22',
    active: false,
  },
  {
    id: 16,
    name: 'Sophia Walker',
    department: 'Design',
    salary: 73_000,
    startDate: '2021-10-10',
    active: true,
  },
  {
    id: 17,
    name: 'Ryan Adams',
    department: 'Marketing',
    salary: 66_000,
    startDate: '2023-03-05',
    active: true,
  },
  {
    id: 18,
    name: 'Mia Thompson',
    department: 'Product',
    salary: 79_000,
    startDate: '2020-08-17',
    active: true,
  },
  {
    id: 19,
    name: 'Ethan Young',
    department: 'Sales',
    salary: 74_000,
    startDate: '2022-04-30',
    active: false,
  },
  {
    id: 20,
    name: 'Ava Green',
    department: 'Engineering',
    salary: 82_000,
    startDate: '2021-06-28',
    active: true,
  },
  {
    id: 21,
    name: 'Liam Carter',
    department: 'Engineering',
    salary: 88_000,
    startDate: '2023-07-19',
    active: true,
  },
  {
    id: 22,
    name: 'Isabella Wright',
    department: 'Design',
    salary: 71_000,
    startDate: '2022-02-28',
    active: true,
  },
  {
    id: 23,
    name: 'Noah Hill',
    department: 'Product',
    salary: 84_000,
    startDate: '2020-10-05',
    active: false,
  },
  {
    id: 24,
    name: 'Chloe Turner',
    department: 'Marketing',
    salary: 68_000,
    startDate: '2023-04-12',
    active: true,
  },
  {
    id: 25,
    name: 'Lucas Scott',
    department: 'Sales',
    salary: 72_000,
    startDate: '2021-12-15',
    active: true,
  },
  {
    id: 26,
    name: 'Grace Parker',
    department: 'Engineering',
    salary: 86_000,
    startDate: '2020-06-22',
    active: true,
  },
  {
    id: 27,
    name: 'Mason Lewis',
    department: 'Design',
    salary: 70_000,
    startDate: '2022-08-09',
    active: false,
  },
  {
    id: 28,
    name: 'Harper Allen',
    department: 'Product',
    salary: 81_000,
    startDate: '2021-05-03',
    active: true,
  },
  {
    id: 29,
    name: 'Elijah Brooks',
    department: 'Marketing',
    salary: 67_000,
    startDate: '2023-09-25',
    active: true,
  },
  {
    id: 30,
    name: 'Amelia Cook',
    department: 'Sales',
    salary: 75_000,
    startDate: '2020-11-30',
    active: false,
  },
];
