# This is a conceptual example of a workflow to publish an application to different environments
# This workflow is triggered by another workflow which triggers the publish workflow with the required parameters
# see release.yml

name: Publish Application

permissions:
  id-token: write
  contents: read

on:
  workflow_call:  
    inputs:
      working-directory:
        description: 'Working directory for the app'
        required: true
        type: string
      tag:
        description: 'Tag to publish (preview | latest)'
        required: true
        default: 'latest'
        type: string

env:
  working-directory: ${{ inputs.working-directory }}
  tag: ${{ inputs.tag }}

jobs:
  build:
    name: Bundle application
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bundle.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup node and install dependencies
      - name: Setupe node and install dependencies
        uses: ./.github/workflows/actions/node-setup

      # Build the application and pack it
      - name: Bundle application
        id: bundle
        working-directory: ${{ env.working-directory }}
        run: |
          pnpm exec fusion-framework-cli app build-pack
          echo "version=$(cat ./dist/app-manifest.json | jq -r .version)" >> $GITHUB_OUTPUT

      # Upload the build artifact
      - name: Upload packed app as artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: ${{ env.working-directory }}/app-bundle.zip

  deploy:
    needs: build
    name: Publish application
    runs-on: ubuntu-latest
    # This is a matrix strategy to run the job for each environment
    # Run in sequence to await required checks on environments
    strategy:
      max-parallel: 1
      matrix:
        environment: ['CI'] #, 'FQA', 'FPRD']
    environment: ${{ matrix.environment }}
    env:
      version: ${{ needs.build.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Required to generate configuration for the app in the selected environment
      # Developers might need to expose some secrets or variables to configuration specific to the environment
      - name: Setupe node and install dependencies
        uses: ./.github/workflows/actions/node-setup

      # Download the build artifact from the previous job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-bundle
          path: ${{ env.working-directory }}

      # Sign in to Azure with service principal
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      # Get access token for the app service
      - name: Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: >+
            ACCESS_TOKEN = $(az account get-access-token 
              --scope ${{ vars.APP_PUBLISH_SCOPE }} 
              --query accessToken 
              --output tsv
            )

            echo "FUSION_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      # Publish the application for the selected environment
      - name: Publish application
        working-directory: ${{ env.working-directory }}
        run: >+
          pnpm exec fusion-framework-cli app build-upload 
            --bundle app-bundle.zip
            --env ${{ matrix.environment }}

      # Tag the application for the selected environment
      - name: Tag application
        working-directory: ${{ env.working-directory }}
        run: >+
          pnpm exec fusion-framework-cli app build-tag 
            --env ${{ matrix.environment }}
            --tag ${{ env.tag }}
            --version ${{ env.version }}

      # Publish the configuration for the app for the selected environment
      - name: Publish configuration
        working-directory: ${{ env.working-directory }}
        run: >+
          pnpm exec fusion-framework-cli app build-config 
            --config app.config-${{ matrix.environment }}.ts 
            --publish ${{ env.version }} 
            --env ${{ matrix.environment }}
