# This is a example of a workflow that will trigger when a release is created in the repository.
# Github will trigger this workflow when a release is created and the release is published, 
# for example when using framework like Changeset
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Assume that the tag of a release is the ${APP_KEY}@${VERSION}
      - name: Extract appkey
        id: extract_appkey
        run: echo "APP_KEY=$(echo ${{ github.ref_name }} | cut -d'@' -f 1)" >> $GITHUB_ENV

      # Dispatch the publish workflow with the required parameters
      - name: Publish Application
        uses: ./.github/workflows/publish
        with:
          # Asume that the the appkey is the same as the subdirectory under 'packages'
          working_directory: 'packages/${{ steps.extract_appkey.outputs.APP_KEY }}'
          # Use the release event to determine the tag
          tag: ${{ github.event.release.prerelease == true && 'preview' || 'latest' }}