on:
  push:
    branches:
      - feat/fusion-framework/app-alpha

jobs:
  test:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      working-directory: 'apps/demo-app'
      tag: 'preview'